// clang-format off
// *INDENT-OFF*
// Generated by https://github.com/Nigh/picture-to-array
// Version:v1.41
#ifndef _b31f61cf4499240ab038a53ca9040908eda25568_
#define _b31f61cf4499240ab038a53ca9040908eda25568_
#include "bitmap.h"

extern const sBITMAP H4_00_bmp;
extern const sBITMAP H4_01_bmp;
extern const sBITMAP H4_02_bmp;
extern const sBITMAP H4_03_bmp;
extern const sBITMAP H4_04_bmp;
extern const sBITMAP H4_05_bmp;
extern const sBITMAP H4_06_bmp;
extern const sBITMAP H4_07_bmp;
extern const sBITMAP H4_08_bmp;
extern const sBITMAP H4_09_bmp;
extern const sBITMAP H5_bottom_0_bmp;
extern const sBITMAP H5_bottom_1_bmp;
extern const sBITMAP H5_bottom_2_bmp;
extern const sBITMAP H5_bottom_3_bmp;
extern const sBITMAP H5_bottom_4_bmp;
extern const sBITMAP H5_bottom_5_bmp;
extern const sBITMAP H5_bottom_6_bmp;
extern const sBITMAP H5_bottom_7_bmp;
extern const sBITMAP H5_bottom_8_bmp;
extern const sBITMAP H5_bottom_9_bmp;
extern const sBITMAP H6_a0_bmp;
extern const sBITMAP H6_a1_bmp;
extern const sBITMAP H6_a2_bmp;
extern const sBITMAP H6_a3_bmp;
extern const sBITMAP H6_a4_bmp;
extern const sBITMAP H6_a5_bmp;
extern const sBITMAP H6_a6_bmp;
extern const sBITMAP H6_a7_bmp;
extern const sBITMAP H6_a8_bmp;
extern const sBITMAP H6_a9_bmp;
extern const sBITMAP H7_00_bmp;
extern const sBITMAP H7_01_bmp;
extern const sBITMAP H7_02_bmp;
extern const sBITMAP H7_03_bmp;
extern const sBITMAP H7_04_bmp;
extern const sBITMAP H7_05_bmp;
extern const sBITMAP H7_06_bmp;
extern const sBITMAP H7_07_bmp;
extern const sBITMAP H7_08_bmp;
extern const sBITMAP H7_09_bmp;
extern const sBITMAP X_bmp;
extern const sBITMAP add_bmp;
extern const sBITMAP boot_01_bmp;
extern const sBITMAP boot_02_bmp;
extern const sBITMAP boot_03_bmp;
extern const sBITMAP boot_04_bmp;
extern const sBITMAP boot_05_bmp;
extern const sBITMAP boot_06_bmp;
extern const sBITMAP colon_bmp;
extern const sBITMAP colonEx_bmp;
extern const sBITMAP divide_bmp;
extern const sBITMAP minus_bmp;
extern const sBITMAP ok_bmp;
extern const sBITMAP rslash_bmp;
extern const sBITMAP slash_bmp;
extern const sBITMAP times_bmp;
extern const sBITMAP* H4_array[10];
extern const sBITMAP* H5_bottom_array[10];
extern const sBITMAP* H6_array[10];
extern const sBITMAP* H7_array[10];
extern const sBITMAP* boot_array[6];
#endif
