// clang-format off
// *INDENT-OFF*
// Generated by https://github.com/Nigh/picture-to-array
// Version:v1.41
#include "bitmap.h"

const uint8_t H4_00[5] = {
	0x00, 0x3C, 0x24, 0x3C, 0x00,
};
const sBITMAP H4_00_bmp = {5, 7, H4_00};
const uint8_t H4_01[5] = {
	0x00, 0x04, 0x3C, 0x00, 0x00,
};
const sBITMAP H4_01_bmp = {5, 7, H4_01};
const uint8_t H4_02[5] = {
	0x00, 0x34, 0x2C, 0x20, 0x00,
};
const sBITMAP H4_02_bmp = {5, 7, H4_02};
const uint8_t H4_03[5] = {
	0x00, 0x24, 0x3C, 0x3C, 0x00,
};
const sBITMAP H4_03_bmp = {5, 7, H4_03};
const uint8_t H4_04[5] = {
	0x00, 0x1C, 0x10, 0x3C, 0x00,
};
const sBITMAP H4_04_bmp = {5, 7, H4_04};
const uint8_t H4_05[5] = {
	0x00, 0x20, 0x2C, 0x34, 0x00,
};
const sBITMAP H4_05_bmp = {5, 7, H4_05};
const uint8_t H4_06[5] = {
	0x00, 0x3C, 0x34, 0x34, 0x00,
};
const sBITMAP H4_06_bmp = {5, 7, H4_06};
const uint8_t H4_07[5] = {
	0x00, 0x04, 0x04, 0x3C, 0x00,
};
const sBITMAP H4_07_bmp = {5, 7, H4_07};
const uint8_t H4_08[5] = {
	0x00, 0x3C, 0x3C, 0x3C, 0x00,
};
const sBITMAP H4_08_bmp = {5, 7, H4_08};
const uint8_t H4_09[5] = {
	0x00, 0x2C, 0x2C, 0x3C, 0x00,
};
const sBITMAP H4_09_bmp = {5, 7, H4_09};
const uint8_t H5_bottom_0[5] = {
	0x00, 0x7C, 0x44, 0x7C, 0x00,
};
const sBITMAP H5_bottom_0_bmp = {5, 7, H5_bottom_0};
const uint8_t H5_bottom_1[5] = {
	0x00, 0x48, 0x7C, 0x40, 0x00,
};
const sBITMAP H5_bottom_1_bmp = {5, 7, H5_bottom_1};
const uint8_t H5_bottom_2[5] = {
	0x00, 0x6C, 0x54, 0x4C, 0x00,
};
const sBITMAP H5_bottom_2_bmp = {5, 7, H5_bottom_2};
const uint8_t H5_bottom_3[5] = {
	0x00, 0x44, 0x54, 0x6C, 0x00,
};
const sBITMAP H5_bottom_3_bmp = {5, 7, H5_bottom_3};
const uint8_t H5_bottom_4[5] = {
	0x00, 0x38, 0x24, 0x7C, 0x20,
};
const sBITMAP H5_bottom_4_bmp = {5, 7, H5_bottom_4};
const uint8_t H5_bottom_5[5] = {
	0x00, 0x4C, 0x54, 0x74, 0x00,
};
const sBITMAP H5_bottom_5_bmp = {5, 7, H5_bottom_5};
const uint8_t H5_bottom_6[5] = {
	0x00, 0x7C, 0x54, 0x74, 0x00,
};
const sBITMAP H5_bottom_6_bmp = {5, 7, H5_bottom_6};
const uint8_t H5_bottom_7[5] = {
	0x00, 0x64, 0x14, 0x0C, 0x00,
};
const sBITMAP H5_bottom_7_bmp = {5, 7, H5_bottom_7};
const uint8_t H5_bottom_8[5] = {
	0x00, 0x6C, 0x54, 0x6C, 0x00,
};
const sBITMAP H5_bottom_8_bmp = {5, 7, H5_bottom_8};
const uint8_t H5_bottom_9[5] = {
	0x00, 0x5C, 0x54, 0x7C, 0x00,
};
const sBITMAP H5_bottom_9_bmp = {5, 7, H5_bottom_9};
const uint8_t H6_a0[5] = {
	0x00, 0x1E, 0x21, 0x21, 0x1E,
};
const sBITMAP H6_a0_bmp = {5, 7, H6_a0};
const uint8_t H6_a1[5] = {
	0x00, 0x22, 0x3F, 0x20, 0x00,
};
const sBITMAP H6_a1_bmp = {5, 7, H6_a1};
const uint8_t H6_a2[5] = {
	0x00, 0x32, 0x29, 0x25, 0x22,
};
const sBITMAP H6_a2_bmp = {5, 7, H6_a2};
const uint8_t H6_a3[5] = {
	0x00, 0x21, 0x25, 0x25, 0x1A,
};
const sBITMAP H6_a3_bmp = {5, 7, H6_a3};
const uint8_t H6_a4[5] = {
	0x00, 0x0F, 0x08, 0x08, 0x3F,
};
const sBITMAP H6_a4_bmp = {5, 7, H6_a4};
const uint8_t H6_a5[5] = {
	0x00, 0x27, 0x25, 0x25, 0x19,
};
const sBITMAP H6_a5_bmp = {5, 7, H6_a5};
const uint8_t H6_a6[5] = {
	0x00, 0x1E, 0x25, 0x25, 0x19,
};
const sBITMAP H6_a6_bmp = {5, 7, H6_a6};
const uint8_t H6_a7[5] = {
	0x00, 0x01, 0x39, 0x05, 0x03,
};
const sBITMAP H6_a7_bmp = {5, 7, H6_a7};
const uint8_t H6_a8[5] = {
	0x00, 0x1A, 0x25, 0x25, 0x1A,
};
const sBITMAP H6_a8_bmp = {5, 7, H6_a8};
const uint8_t H6_a9[5] = {
	0x00, 0x12, 0x25, 0x25, 0x1E,
};
const sBITMAP H6_a9_bmp = {5, 7, H6_a9};
const uint8_t H7_00[5] = {
	0x3E, 0x51, 0x49, 0x45, 0x3E,
};
const sBITMAP H7_00_bmp = {5, 7, H7_00};
const uint8_t H7_01[5] = {
	0x44, 0x42, 0x7F, 0x40, 0x40,
};
const sBITMAP H7_01_bmp = {5, 7, H7_01};
const uint8_t H7_02[5] = {
	0x62, 0x51, 0x49, 0x49, 0x46,
};
const sBITMAP H7_02_bmp = {5, 7, H7_02};
const uint8_t H7_03[5] = {
	0x22, 0x41, 0x49, 0x49, 0x36,
};
const sBITMAP H7_03_bmp = {5, 7, H7_03};
const uint8_t H7_04[5] = {
	0x18, 0x14, 0x12, 0x7F, 0x10,
};
const sBITMAP H7_04_bmp = {5, 7, H7_04};
const uint8_t H7_05[5] = {
	0x2F, 0x49, 0x49, 0x49, 0x31,
};
const sBITMAP H7_05_bmp = {5, 7, H7_05};
const uint8_t H7_06[5] = {
	0x3E, 0x49, 0x49, 0x49, 0x32,
};
const sBITMAP H7_06_bmp = {5, 7, H7_06};
const uint8_t H7_07[5] = {
	0x01, 0x71, 0x09, 0x05, 0x03,
};
const sBITMAP H7_07_bmp = {5, 7, H7_07};
const uint8_t H7_08[5] = {
	0x36, 0x49, 0x49, 0x49, 0x36,
};
const sBITMAP H7_08_bmp = {5, 7, H7_08};
const uint8_t H7_09[5] = {
	0x26, 0x49, 0x49, 0x49, 0x3E,
};
const sBITMAP H7_09_bmp = {5, 7, H7_09};
const uint8_t H7_Sq_0[5] = {
	0x7F, 0x7F, 0x63, 0x7F, 0x7F,
};
const sBITMAP H7_Sq_0_bmp = {5, 7, H7_Sq_0};
const uint8_t H7_Sq_1[5] = {
	0x00, 0x03, 0x7F, 0x7F, 0x00,
};
const sBITMAP H7_Sq_1_bmp = {5, 7, H7_Sq_1};
const uint8_t H7_Sq_2[5] = {
	0x7B, 0x7B, 0x6B, 0x6F, 0x6F,
};
const sBITMAP H7_Sq_2_bmp = {5, 7, H7_Sq_2};
const uint8_t H7_Sq_3[5] = {
	0x63, 0x6B, 0x6B, 0x7F, 0x7F,
};
const sBITMAP H7_Sq_3_bmp = {5, 7, H7_Sq_3};
const uint8_t H7_Sq_4[5] = {
	0x1F, 0x1F, 0x10, 0x7F, 0x7F,
};
const sBITMAP H7_Sq_4_bmp = {5, 7, H7_Sq_4};
const uint8_t H7_Sq_5[5] = {
	0x6F, 0x6F, 0x6B, 0x6B, 0x7B,
};
const sBITMAP H7_Sq_5_bmp = {5, 7, H7_Sq_5};
const uint8_t H7_Sq_6[5] = {
	0x7F, 0x7F, 0x6B, 0x7B, 0x7B,
};
const sBITMAP H7_Sq_6_bmp = {5, 7, H7_Sq_6};
const uint8_t H7_Sq_7[5] = {
	0x03, 0x03, 0x03, 0x7F, 0x7F,
};
const sBITMAP H7_Sq_7_bmp = {5, 7, H7_Sq_7};
const uint8_t H7_Sq_8[5] = {
	0x7F, 0x7F, 0x6B, 0x7F, 0x7F,
};
const sBITMAP H7_Sq_8_bmp = {5, 7, H7_Sq_8};
const uint8_t H7_Sq_9[5] = {
	0x6F, 0x6F, 0x6B, 0x7F, 0x7F,
};
const sBITMAP H7_Sq_9_bmp = {5, 7, H7_Sq_9};
const uint8_t X[5] = {
	0x22, 0x14, 0x08, 0x14, 0x22,
};
const sBITMAP X_bmp = {5, 7, X};
const uint8_t add[5] = {
	0x00, 0x08, 0x1C, 0x08, 0x00,
};
const sBITMAP add_bmp = {5, 7, add};
const uint8_t boot_01[5] = {
	0x08, 0x08, 0x08, 0x08, 0x08,
};
const sBITMAP boot_01_bmp = {5, 7, boot_01};
const uint8_t boot_02[5] = {
	0x1C, 0x1C, 0x1C, 0x1C, 0x1C,
};
const sBITMAP boot_02_bmp = {5, 7, boot_02};
const uint8_t boot_03[5] = {
	0x3E, 0x3E, 0x3E, 0x3E, 0x3E,
};
const sBITMAP boot_03_bmp = {5, 7, boot_03};
const uint8_t boot_04[5] = {
	0x7F, 0x7F, 0x7F, 0x7F, 0x7F,
};
const sBITMAP boot_04_bmp = {5, 7, boot_04};
const uint8_t boot_05[5] = {
	0x7F, 0x7F, 0x00, 0x7F, 0x7F,
};
const sBITMAP boot_05_bmp = {5, 7, boot_05};
const uint8_t boot_06[5] = {
	0x7F, 0x00, 0x00, 0x00, 0x7F,
};
const sBITMAP boot_06_bmp = {5, 7, boot_06};
const uint8_t colon[5] = {
	0x00, 0x00, 0x14, 0x00, 0x00,
};
const sBITMAP colon_bmp = {5, 7, colon};
const uint8_t colonEx[5] = {
	0x00, 0x00, 0x36, 0x36, 0x00,
};
const sBITMAP colonEx_bmp = {5, 7, colonEx};
const uint8_t divide[5] = {
	0x00, 0x00, 0x3E, 0x00, 0x00,
};
const sBITMAP divide_bmp = {5, 7, divide};
const uint8_t minus[5] = {
	0x00, 0x08, 0x08, 0x08, 0x00,
};
const sBITMAP minus_bmp = {5, 7, minus};
const uint8_t ok[5] = {
	0x00, 0x77, 0x25, 0x57, 0x00,
};
const sBITMAP ok_bmp = {5, 7, ok};
const uint8_t rslash[5] = {
	0x00, 0x04, 0x08, 0x10, 0x00,
};
const sBITMAP rslash_bmp = {5, 7, rslash};
const uint8_t slash[5] = {
	0x00, 0x10, 0x08, 0x04, 0x00,
};
const sBITMAP slash_bmp = {5, 7, slash};
const uint8_t times[5] = {
	0x00, 0x14, 0x08, 0x14, 0x00,
};
const sBITMAP times_bmp = {5, 7, times};

const sBITMAP* H4_array[10] = {
	&H4_00_bmp, // 00.png
	&H4_01_bmp, // 01.png
	&H4_02_bmp, // 02.png
	&H4_03_bmp, // 03.png
	&H4_04_bmp, // 04.png
	&H4_05_bmp, // 05.png
	&H4_06_bmp, // 06.png
	&H4_07_bmp, // 07.png
	&H4_08_bmp, // 08.png
	&H4_09_bmp, // 09.png
};

const sBITMAP* H5_bottom_array[10] = {
	&H5_bottom_0_bmp, // 0.png
	&H5_bottom_1_bmp, // 1.png
	&H5_bottom_2_bmp, // 2.png
	&H5_bottom_3_bmp, // 3.png
	&H5_bottom_4_bmp, // 4.png
	&H5_bottom_5_bmp, // 5.png
	&H5_bottom_6_bmp, // 6.png
	&H5_bottom_7_bmp, // 7.png
	&H5_bottom_8_bmp, // 8.png
	&H5_bottom_9_bmp, // 9.png
};

const sBITMAP* H6_array[10] = {
	&H6_a0_bmp, // a0.png
	&H6_a1_bmp, // a1.png
	&H6_a2_bmp, // a2.png
	&H6_a3_bmp, // a3.png
	&H6_a4_bmp, // a4.png
	&H6_a5_bmp, // a5.png
	&H6_a6_bmp, // a6.png
	&H6_a7_bmp, // a7.png
	&H6_a8_bmp, // a8.png
	&H6_a9_bmp, // a9.png
};

const sBITMAP* H7_array[10] = {
	&H7_00_bmp, // 00.png
	&H7_01_bmp, // 01.png
	&H7_02_bmp, // 02.png
	&H7_03_bmp, // 03.png
	&H7_04_bmp, // 04.png
	&H7_05_bmp, // 05.png
	&H7_06_bmp, // 06.png
	&H7_07_bmp, // 07.png
	&H7_08_bmp, // 08.png
	&H7_09_bmp, // 09.png
};

const sBITMAP* H7_Sq_array[10] = {
	&H7_Sq_0_bmp, // 0.png
	&H7_Sq_1_bmp, // 1.png
	&H7_Sq_2_bmp, // 2.png
	&H7_Sq_3_bmp, // 3.png
	&H7_Sq_4_bmp, // 4.png
	&H7_Sq_5_bmp, // 5.png
	&H7_Sq_6_bmp, // 6.png
	&H7_Sq_7_bmp, // 7.png
	&H7_Sq_8_bmp, // 8.png
	&H7_Sq_9_bmp, // 9.png
};

const sBITMAP* boot_array[6] = {
	&boot_01_bmp, // 01.png
	&boot_02_bmp, // 02.png
	&boot_03_bmp, // 03.png
	&boot_04_bmp, // 04.png
	&boot_05_bmp, // 05.png
	&boot_06_bmp, // 06.png
};
